### ISSUE TITLE
Missing rack session in v4

### ISSUE THREAD

**Issue by waghanza** [soveran/cuba#103]
Hi @soveran,

With the last version, I have
```ruby
/usr/src/app # bundle exec puma
Puma starting in single mode...
* Puma version: 6.1.0 (ruby 3.2.1-p31) ("The Way Up")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 7
! Unable to load application: LoadError: cannot load such file -- rack/session
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rack/session (LoadError)
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/cuba-4.0.0/lib/cuba.rb:3:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/src/app/app.rb:3:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-3.0.4.1/lib/rack/builder.rb:103:in `eval'
	from /usr/local/bundle/gems/rack-3.0.4.1/lib/rack/builder.rb:103:in `new_from_string'
	from /usr/local/bundle/gems/rack-3.0.4.1/lib/rack/builder.rb:94:in `load_file'
	from /usr/local/bundle/gems/rack-3.0.4.1/lib/rack/builder.rb:64:in `parse_file'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/configuration.rb:365:in `load_rackup'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/configuration.rb:287:in `app'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/runner.rb:158:in `load_and_bind'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/single.rb:44:in `run'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/launcher.rb:189:in `run'
	from /usr/local/bundle/gems/puma-6.1.0/lib/puma/cli.rb:75:in `run'
	from /usr/local/bundle/gems/puma-6.1.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:25:in `load'
	from /usr/local/bundle/bin/puma:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:45:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/libexec/bundle:33:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
```

seems that **rack-session** is missing.

Regards,

Related to https://github.com/the-benchmarker/web-frameworks/pull/6148

**Comment by soveran** [comment]
Hey @waghanza, thanks for your help! I've just pushed version 4.0.1 which adds rack-session as a dependency. I'm very sorry for the oversight!

**Comment by waghanza** [comment]
Thanks @soveran for your quick reply, I've update results in https://web-frameworks-benchmark.netlify.app/result?l=ruby
